server:
  port: 8024
spring:
  application:
    name: antares-gateway # 服务名称
  profiles:
    active: dev # 开发环境
  cloud:
    nacos:
      server-addr: 172.17.0.3:8848 # Nacos地址
      username: nacos
      password: 123456
      discovery:
        namespace: 4a9711ba-ff63-4793-93e6-af052ba1bc78
        group: rest
    gateway:
      routes:
        # 前端项目都带/api前缀
        - id: user_route
          uri: lb://antares-user
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: judge_route
          uri: lb://antares-judge
          predicates:
            - Path=/api/judge/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: sandbox_route
          uri: lb://antares-code-sandbox
          predicates:
            - Path=/api/sandbox/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}