server:
  port: 8011
  servlet:
    context-path: /user
spring:
  application:
    name: antares-user
  profiles:
    active: dev # 开发环境
  cloud:
    nacos:
      server-addr: 172.17.0.3:8848 # Nacos地址
      username: nacos
      password: 123456
      config:
        namespace: 4a9711ba-ff63-4793-93e6-af052ba1bc78
        group: rest
      discovery:
        namespace: 4a9711ba-ff63-4793-93e6-af052ba1bc78
        group: rest
  config: # nacos作为配置中心的配置
    import:
      - "optional:nacos:${spring.application.name}-${spring.profiles.active}.yml"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.1:3306/antares_oj?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 172.17.0.1
    port: 6379
    password: 123456
  mail: # 邮件配置
    host: smtp.qq.com # 邮件服务器地址
    username: 123456@qq.com # 你的邮箱地址
    password: 123456 # 授权码
    default-encoding: utf-8 # 编码格式
    protocol: smtp # 协议
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 当数据库字段使用_连接时这里配置成true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置日志
  mapper-locations: classpath*:/mapper/**/*.xml # 配置xml文件位置，这里是和@mapperscan注解的作用是不同的，后者是指定dao的位置
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
dubbo:
  application:
    name: "${spring.application.name}-dubbo"
    logger: slf4j
    protocol: tri
    qos-enable: false
  registry:
    address: nacos://172.17.0.3:8848?username=nacos&password=123456&namespace=4a9711ba-ff63-4793-93e6-af052ba1bc78&group=dubbo
    register-mode: instance
  protocol:
    name: tri
    port: 8031
antares:
  domain: fffu.fun
  user:
    secret-key: 123456
    token-expire-hours: 168