POST http://127.0.0.1:8013/sandbox/execute
Content-Type: application/json

{
  "code": "public class Main {public static void main(String[] args) {byte[] memoryBlock = new byte[512 * 1024 * 1024];System.out.println(\"Successfully allocated 256MB of memory.\");}}",
  "language": "Java"
}