POST http://127.0.0.1:8013/sandbox/execute
Content-Type: application/json

{
  "inputList": [null, null, null],
  "code": "public class Main {public static void main(String[] args) {System.out.println(\"Hello, World!\");}}",
  "language": "java"
}