POST http://127.0.0.1:8012/judge/run
Content-Type: application/json
Cookie: token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjE4NDg2NTMxNDk4MTI5NTMwODgsInVzZXJSb2xlIjoiYWRtaW4iLCJleHAiOjE3MzExMjI3MTJ9.DvF_P5zaSqoz-3Agu876VDIBwXqkAOncmvRznsmZZ8Y

{
  "inputList": ["1 2", "2 3", " 4 5"],
  "code": "import java.util.Scanner;public class Main {public static void main(String args[]) throws Exception {try (Scanner cin = new Scanner(System.in)) {int a = cin.nextInt(), b = cin.nextInt();System.out.println(a + b);}}}",
  "language": "java"
}