GET http://127.0.0.1:8024/api/judge/problem/1/vo 
Content-Type: application/json
Cookie: token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjE4NDg2NTMxNDk4MTI5NTMwODgsInVzZXJSb2xlIjoiYWRtaW4iLCJleHAiOjE3NDU1NzAwNDZ9.Xn1DvQk9NefxVWwHVwi88gGFEmIyfj0bk_wY5dr3-cs