server:
  port: 8013
  servlet:
    context-path: /sandbox
spring:
  application:
    name: antares-code-sandbox
  profiles:
    active: dev # 开发环境
  cloud:
    nacos:
      server-addr: 172.17.0.3:8848 # Nacos地址
      username: nacos
      password: 123456
      config:
        namespace: 4a9711ba-ff63-4793-93e6-af052ba1bc78
        group: rest
      discovery:
        namespace: 4a9711ba-ff63-4793-93e6-af052ba1bc78
        group: rest
  config: # nacos作为配置中心的配置
    import:
      - "optional:nacos:${spring.application.name}-${spring.profiles.active}.yml"
# logging:
#   level:
#     com.github.dockerjava: DEBUG  # 设置docker-java的日志级别
antares:
  code-sandbox:
    timeout: 1000
    filename: Main
    type: docker
    docker: # 当type设置为docker时需要进行配置
      jdk-image: openjdk:8-alpine
      host: tcp://172.17.0.1:2375
      connect-timeout: 30
      response-timeout: 30
      memory-limit: 128
      cpu-count: 4
      save-path: /docker/code/java/antares-oj-backend/tmpCode
      mem-script: /docker/code/java/antares-oj-backend/script/mem.sh
